### ISSUE TITLE
Update required for next HA Version

### ISSUE THREAD

**Issue by sebcaps** [kamaradclimber/rte-ecowatt#58] opened 2023-02-02 17:52 UTC
Recently updated to HA 2023.2.0 and the following warning message raised in logs
```Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 18:42:02 (1 occurrences)
Last logged: 18:42:02

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for rte_ecowatt using this method at custom_components/rte_ecowatt/__init__.py, line 65: hass.config_entries.async_setup_platforms(
```

Thus it seems that the component requires update to continue working after release 2023.3.
Just a warning for the moment.
I'll see if I can give a try fixing it.  For the moment jsut logging :-)

**Comment by kamaradclimber** [comment] 2023-02-02 17:53
Hello, this is a duplicate of  #56 , fix is in the pre-release (I've not tested it yet on my own infra)

**Closed** 2023-02-02 17:53 UTC

**Comment by sebcaps** [comment] 2023-02-02 17:57
My bad, missed looking to closed issue ;-)
