### ISSUE TITLE
Repository not Found

### ISSUE THREAD

**Issue by StephaneRod** [kamaradclimber/rte-ecowatt#6] opened 2022-10-03 18:49 UTC
your HACS integration link seems not working

**Comment by Nemesis24** [comment] 2022-10-04 06:48
This is the same for me !!

**Comment by kamaradclimber** [comment] 2022-10-04 08:23
Indeed it seems to require to this repository to be added in hacs first.
I'll work on this this evening but it might require some time to be fixed because it requires sequential PRs in https://github.com/home-assistant/brands and https://github.com/home-assistant/brands

**Comment by kamaradclimber** [comment] 2022-10-05 15:23
https://github.com/hacs/default/pull/1529 has been opened, I think the issue will disappear after it will be merged.

**Comment by HermesHonshappo** [comment] 2022-10-21 12:20
Hello
Any update? Is there a link to be able to add the repository manually in HACS?

**Comment by kamaradclimber** [comment] 2022-10-21 12:35
I'm still waiting for https://github.com/hacs/default/pull/1529. In the meantime you can follow instructions on https://hacs.xyz/docs/faq/custom_repositories/

**Comment by floreo** [comment] 2022-10-21 18:13
Hello,

I installed rte-ecowatt with the described method above since hacs is not yet up to date but the interface is not prompting me anything to define client_id and client_secret, should I write it in configuration.yaml ?
Thanks.

**Comment by kamaradclimber** [comment] 2022-10-21 18:15
You need to go in Settings-> "Devices & Services" as for any integration configured from the UI.

**Comment by floreo** [comment] 2022-10-21 19:13
Oh that's right, sorry for the noise, it's configured now, thanks !

**Closed** 2022-10-24 14:08 UTC

**Comment by kamaradclimber** [comment] 2022-10-24 14:33
Repository has been added and will be published in next hacs version.

**Comment by floreo** [comment] 2022-10-24 17:28
Confirmed ! Thanks :)
